/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Allison
 */
public class RegistrarPersona extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPersona
     */
    public RegistrarPersona() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("#FBCF86")); //F5CC7E o F5D28E o F3CC89
        scaleImage();
    }
    public void scaleImage(){
        ImageIcon icon = new ImageIcon("/Images/back.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(btnBack.getWidth(), btnBack.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        btnBack.setIcon(scaledIcon);
        
    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtFieldFisrtname = new javax.swing.JTextField();
        lblFirstname = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        lblLastname = new javax.swing.JLabel();
        txtFieldLastname = new javax.swing.JTextField();
        lblBirthdate = new javax.swing.JLabel();
        txtFiieldID = new javax.swing.JTextField();
        btnRegAddress = new javax.swing.JButton();
        btnRegisterEmail = new javax.swing.JButton();
        lblID1 = new javax.swing.JLabel();
        txtFieldBirthdate = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblLinea = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 213, 178));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Register People");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 240, 45));
        getContentPane().add(txtFieldFisrtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 101, -1));

        lblFirstname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(0, 0, 0));
        lblFirstname.setText("Fisrtname:");
        getContentPane().add(lblFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 87, 22));

        btnRegister.setBackground(new java.awt.Color(219, 107, 92));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(153, 51, 0));
        btnRegister.setText("Register");
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 130, 40));

        lblLastname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastname.setForeground(new java.awt.Color(0, 0, 0));
        lblLastname.setText("Lastname:");
        getContentPane().add(lblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 87, 22));
        getContentPane().add(txtFieldLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 101, -1));

        lblBirthdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBirthdate.setForeground(new java.awt.Color(0, 0, 0));
        lblBirthdate.setText("Birthdate");
        getContentPane().add(lblBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 87, 22));
        getContentPane().add(txtFiieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 97, -1));

        btnRegAddress.setBackground(new java.awt.Color(219, 107, 92));
        btnRegAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegAddress.setForeground(new java.awt.Color(153, 51, 0));
        btnRegAddress.setText("Register Address");
        getContentPane().add(btnRegAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 133, -1));

        btnRegisterEmail.setBackground(new java.awt.Color(219, 107, 92));
        btnRegisterEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegisterEmail.setForeground(new java.awt.Color(153, 51, 0));
        btnRegisterEmail.setText("Register E-mail");
        getContentPane().add(btnRegisterEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 123, -1));

        lblID1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblID1.setForeground(new java.awt.Color(0, 0, 0));
        lblID1.setText("ID Number:");
        getContentPane().add(lblID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 87, 22));
        getContentPane().add(txtFieldBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 100, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("E-mail");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 87, 24));

        lblAddress1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAddress1.setForeground(new java.awt.Color(0, 0, 0));
        lblAddress1.setText("Address;");
        getContentPane().add(lblAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 87, 22));

        btnBack.setBackground(new java.awt.Color(219, 107, 92));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("⇦");
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        lblLinea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLinea.setForeground(new java.awt.Color(0, 0, 0));
        lblLinea.setText("----------------------------------------------");
        getContentPane().add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/personaanimada1.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 482, -1));

        jPanel1.setBackground(new java.awt.Color(242, 205, 92));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 350, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegAddress;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtFieldBirthdate;
    private javax.swing.JTextField txtFieldFisrtname;
    private javax.swing.JTextField txtFieldLastname;
    private javax.swing.JTextField txtFiieldID;
    // End of variables declaration//GEN-END:variables
}
